# Generated by Django 6.0.3 on 2026-03-04 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paciente', models.CharField(max_length=100)),
                ('medico', models.CharField(max_length=100)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('hora', models.TimeField()),
                ('motivo', models.TextField(help_text='Escriba el motivo de la cita')),
                ('estado', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CrearCita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_cita', models.CharField(max_length=100)),
                ('medico', models.CharField(max_length=100)),
                ('paciente', models.CharField(max_length=100)),
                ('agenda', models.DateTimeField()),
                ('estado', models.CharField(default='Pendiente', max_length=20)),
            ],
        ),
    ]
